In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [2]:
df = pd.read_csv('house.csv',index_col=[0])

### cleaning

###### dealing with missing values

In [3]:
features_with_NAN = [features for features in df.columns if df[features].isnull().sum()>1]

for feature in features_with_NAN:
    print(feature ,np.round(df[feature].isnull().mean(), 4) , '% missing values')

Title 0.0294 % missing values
Location 0.0294 % missing values
Description 0.0294 % missing values
Price 0.2802 % missing values

In [4]:
df = df.dropna()
df.reset_index(drop=True, inplace=True)

###### spliting data

In [5]:
df['City'] = df['Location'].str[-6:]

In [6]:
def get_location(data):
    if len(data.split(' '))>1:
        return data.split(' ')[0:2]
    else: 
        return data

df["Location"] = df["Location"].apply(lambda x : get_location(x))

In [7]:
def exact_location(data):
    if(data[1] == 'à\n\t\t\t\tTanger' or data[1] == '1'):
        return data[0]
    else:
        return f"{data[0]} {data[1]}"
df["Location"] = df["Location"].apply(lambda x : exact_location(x))

###### dealing with price

In [8]:
df["Price"] = df["Price"].apply(lambda x : x.replace(u'\xa0', u''))

In [9]:
df["Currency"] = df["Price"].str[-2:]
df["Price"] = df["Price"].str[:-2]

In [10]:
df["Price"] = df["Price"].apply(lambda x : x.replace(u'E', u''))
df["Price"] = df["Price"].astype(int)

###### dealing with description

In [11]:
data = df.copy()

def sliting(data):
    return data.split('//')

data["Description"] = data["Description"].apply(lambda x : sliting(x))

data.head(50)

,Title,Location,Security,Garage,Concierge,Description,Price,City,Currency
0,Appartement avec vue mer depuis toutes les pièces,Centre,0,0,0,"[95\n\t\t\t\t\tm², 3 Pièces, 2 Chambres, 2 Sal...",2200000,Tanger,DH
1,"Studio de 43m² en vente, Résidence Panama",Malabata,1,0,0,"[43\n\t\t\t\t\tm², 1 Pièce, 1 Chambre, 1 Salle...",602000,Tanger,DH
2,Appartement de 94m² en vente Résidence Al Bahja,Tanja Balia,0,0,0,"[94\n\t\t\t\t\tm², 4 Pièces, 3 Chambres, 2 Sal...",694575,Tanger,DH
3,Appartement de 110m² en vente Les Jardins de M...,Mesnana,0,0,0,"[110\n\t\t\t\t\tm², 4 Pièces, 3 Chambres, Nouv...",1112000,Tanger,DH
4,Appartement de 75m² en vente Les Jardins de Me...,Mesnana,0,0,0,"[75\n\t\t\t\t\tm², 3 Pièces, 2 Chambres, Nouve...",676000,Tanger,DH
5,Appartement avec terrasse et vue mer,De La,0,0,0,"[129\n\t\t\t\t\tm², 3 Pièces, 2 Chambres, 2 Sa...",2750000,Tanger,DH
6,Magnifique duplex avec vue panoramique sur la ...,Centre,0,0,0,"[223\n\t\t\t\t\tm², 3 Pièces, 2 Chambres, 3 Sa...",3400000,Tanger,DH
7,Superbe appartement de 128m2 avec 3 chambres,Marchan,0,0,0,"[128\n\t\t\t\t\tm², 4 Pièces, 3 Chambres, 2 Sa...",1900000,Tanger,DH
8,"Appartement de 88m² en vente, Résidence Riad Z...",Ahlane,0,0,0,"[70\n\t\t\t\t\tm², 4 Pièces, 2 Chambres, 1 Sal...",580000,Tanger,DH
9,Appartement en vente à Ennasr. Surface totale ...,Ennasr,0,0,0,"[100\n\t\t\t\t\tm², 5 Pièces, 2 Chambres, 2 Sa...",1000000,Tanger,DH
10,Joli appartement en vente à BAYT SAHAFA,Marjane,0,0,0,"[73\n\t\t\t\t\tm², 3 Pièces, 2 Chambres, 1 Sal...",780000,Tanger,DH
11,Appartements moyens standing a vendre,Mesnana,0,0,0,"[66\n\t\t\t\t\tm², 3 Pièces, 2 Chambres, 1 Sal...",550000,Tanger,DH
12,Appartement moyen standing,Tanja Balia,0,0,0,"[58\n\t\t\t\t\tm², 3 Pièces, 2 Chambres, 1 Sal...",403000,Tanger,DH
13,Appartement de 88m² en vente Complexe résident...,Route Nationale,0,0,0,"[88\n\t\t\t\t\tm², 3 Pièces, 2 Chambres, 1 Sal...",651200,Tanger,DH
14,Vente Appartement Tanger BOULEVARD Ref: VA335,Centre,0,0,0,"[72\n\t\t\t\t\tm², 3 Pièces, 2 Chambres, 1 Sal...",1240000,Tanger,DH
15,"Studio de 45m² en vente, Résidence Panama",Malabata,1,0,0,"[45\n\t\t\t\t\tm², 1 Pièce, 1 Chambre, 1 Salle...",630000,Tanger,DH
16,APPARTEMENT 190 m2 de 4 chambres au Boulvard,Administratif,0,0,0,"[190\n\t\t\t\t\tm², 10 Pièces, 4 Chambres, 3 S...",11000,Tanger,DH
17,Ne pas rater votre appartement duplex à vendre,Route Nationale,0,0,0,"[136\n\t\t\t\t\tm², 8 Pièces, 3 Chambres, 2 Sa...",1496000,Tanger,DH
18,Appartement Vide à La Vente Nejma Tanger,Centre,0,0,0,"[144\n\t\t\t\t\tm², 3 Pièces, 2 Chambres, 1 Sa...",2450000,Tanger,DH
19,Appartement de Luxe à La Vente Corniche Tanger,De La,0,0,0,"[105\n\t\t\t\t\tm², 3 Pièces, 2 Chambres, 2 Sa...",2000000,Tanger,DH
20,Appartement à La Vente La wilaya Tanger,Administratif,0,0,1,"[90\n\t\t\t\t\tm², 3 Pièces, 2 Chambres, 1 Sal...",1220000,Tanger,DH
21,Appartement avecTerrasse à Vendre Mojahidin Ta...,Moujahidine,0,0,0,"[257\n\t\t\t\t\tm², 6 Pièces, 5 Chambres, 2 Sa...",2960000,Tanger,DH
22,LUMINEUX Appartement au centre ville a VENDRE,Mozart,0,0,0,"[2 Chambres, 1 Salle de bain, Bon état, 2 Cham...",700000,Tanger,DH
23,Appart F4 de 96 m2 prés de Patisserie Paris,Centre,0,0,0,"[97\n\t\t\t\t\tm², 4 Pièces, 3 Chambres, 2 Sal...",950000,Tanger,DH
24,Appart F3 rénové en vente à Kawacim,Du Golf,0,0,0,"[54\n\t\t\t\t\tm², 3 Pièces, 2 Chambres, 1 Sal...",580000,Tanger,DH
25,Neuf appart F3 de 163m2 vue sur mer,Manar,0,0,0,"[163\n\t\t\t\t\tm², 3 Pièces, 2 Chambres, 2 Sa...",3000000,Tanger,DH
26,Appartement de 115m² en vente Les Jardins de M...,Mesnana,0,0,0,"[115\n\t\t\t\t\tm², 4 Pièces, 3 Chambres, Nouv...",1228000,Tanger,DH
27,Appartement de 61m² en vente Les Jardins de Me...,Mesnana,0,0,0,"[61\n\t\t\t\t\tm², 3 Pièces, 2 Chambres, Nouve...",550000,Tanger,DH
28,Appartement de 112m² en vente Les Jardins de M...,Mesnana,0,0,0,"[112\n\t\t\t\t\tm², 4 Pièces, 3 Chambres, Nouv...",1128000,Tanger,DH
29,Appartement de 72m² en vente Les Jardins de Me...,Mesnana,0,0,0,"[72\n\t\t\t\t\tm², 3 Pièces, 2 Chambres, Nouve...",649000,Tanger,DH
30,Appartement de 85m² en vente Les Jardins de Me...,Mesnana,0,0,0,"[85\n\t\t\t\t\tm², 3 Pièces, 2 Chambres, Nouve...",761000,Tanger,DH
31,Vend appartement à Marjane. Superficie 89 m²,Marjane,0,0,0,"[89\n\t\t\t\t\tm², 3 Pièces, 2 Chambres, 1 Sal...",515666,Tanger,DH
32,Vend appartement à Marjane. Superficie 83 m²,Marjane,0,0,0,"[83\n\t\t\t\t\tm², 3 Pièces, 2 Chambres, 1 Sal...",483558,Tanger,DH
33,Appartement de 117m² en vente Complexe résiden...,Route Nationale,0,0,0,"[117\n\t\t\t\t\tm², 3 Pièces, 2 Chambres, 1 Sa...",830700,Tanger,DH
34,Résidence kawacim (2 ch salon ),Du Golf,0,0,0,"[99\n\t\t\t\t\tm², 3 Pièces, 2 Chambres, 1 Sal...",550000,Tanger,DH
35,Magnifique Appartement à vendre à Lotinord,Marjane,0,0,0,"[100\n\t\t\t\t\tm², 4 Pièces, 3 Chambres, 1 Sa...",1250000,Tanger,DH
36,"Appartement et Duplex à Vendre, Déclaration 10...",Route Nationale,0,0,0,"[136\n\t\t\t\t\tm², 6 Pièces, 3 Chambres, 3 Sa...",1564000,Tanger,DH
37,Exclusif: appartement au centre a vendre,Centre,0,0,0,"[71\n\t\t\t\t\tm², 3 Pièces, 2 Chambres, 1 Sal...",700000,Tanger,DH
38,"Appartement de 109m² en vente, Résidence Qamar",Mister Khouch,0,0,0,"[109\n\t\t\t\t\tm², 4 Pièces, 3 Chambres, 3 Sa...",1362500,Tanger,DH
39,Bel appartement haut standing A vendre: AV15,Centre,0,0,0,"[120\n\t\t\t\t\tm², 6 Pièces, 3 Chambres, 2 Sa...",2280000,Tanger,DH
40,Des Appartements haut standing à Malabata. Tanger,Tanja Balia,0,0,0,"[2 Pièces, 2 Chambres, 2 Salles de bains, Nouv...",950000,Tanger,DH
41,"Studio de 50m² en vente, Résidence Panama",Malabata,1,0,0,"[50\n\t\t\t\t\tm², 1 Pièce, 1 Chambre, 1 Salle...",700000,Tanger,DH
42,Appartement moderne dans le quartier de Malabata,Centre,0,0,0,"[146\n\t\t\t\t\tm², 5 Pièces, 2 Chambres, 2 Sa...",2332000,Tanger,DH
43,Magnifique Riad traditionnel,Médina,0,0,0,"[300\n\t\t\t\t\tm², 14 Pièces, 8 Chambres, 1 S...",7725000,Tanger,DH
44,Grand appartement de 3 chambres,Centre,0,0,0,"[117\n\t\t\t\t\tm², 5 Pièces, 3 Chambres, 1 Sa...",1500000,Tanger,DH
45,Un appartement de 160 mètres carrés dans le ce...,Mozart,0,0,0,"[160\n\t\t\t\t\tm², 5 Pièces, 3 Chambres, 1 Sa...",1526400,Tanger,DH
46,Un magnifique appartement de style colonial,Médina,0,0,0,"[144\n\t\t\t\t\tm², 5 Pièces, 3 Chambres, 1 Sa...",1550000,Tanger,DH
47,Appartement de 115m2 avec un grand potentiel,Mozart,0,0,0,"[115\n\t\t\t\t\tm², 5 Pièces, 3 Chambres, 1 Sa...",1097100,Tanger,DH
48,Appartement à l'achat à De La Plage. 2 chambre...,De La,0,0,0,"[105\n\t\t\t\t\tm², 3 Pièces, 2 Chambres, 2 Sa...",1890000,Tanger,DH
49,Appartement de 88m² en vente Complexe résident...,Route Nationale,0,0,0,"[88\n\t\t\t\t\tm², 3 Pièces, 2 Chambres, 1 Sal...",651200,Tanger,DH

In [12]:
def nmbr_bathroom(data):
    if len(data.split(' '))>1:
        if (data.split(' ')[1]) == "Chambre" or (data.split(' ')[1]) == "Chambres":
            return data
        else:
            return None
    else:
        return None
        
data["Nmbr of rooms"] = data["Description"].apply(lambda x : nmbr_bathroom(x[2]))

In [13]:
def nmbr_bathroom(data):
    if len(data.split(' '))>1:
        if (data.split(' ')[1]) == "Pièce" or (data.split(' ')[1]) == "Pièces":
            return data
        else:
            return None
    else:
        return None
        
data["Nmbr of pieces"] = data["Description"].apply(lambda x : nmbr_bathroom(x[1]))

In [14]:
def nmbr_bathroom(data):
    if len(data.split(' '))>1:
        if (data.split(' ')[1]) == "Salle" or (data.split(' ')[1]) == "Salles":
            return data
        else:
            return None
    else:
        return None
        
data["Nmbr of bathrooms"] = data["Description"].apply(lambda x : nmbr_bathroom(x[3]))

In [15]:
def check_newness(data1, data2):
    if len(data1.split(' '))>1:
        if (data1.split(' ')[1]) == "Salle" or (data1.split(' ')[1]) == "Salles":
            if data2 not in ["Nouveau","Bon état","À rénover"]:
                return None
            else:
                return data2
        else:
            if data1 not in ["Nouveau","Bon état","À rénover"]:
                return None
            else:
                return data1
    else:
        if data1 not in ["Nouveau","Bon état","À rénover"]:
            return None
        else:
            return data1
data["Newness"] = data["Description"].apply(lambda x : check_newness(x[3],x[4]))

In [154]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 465 entries, 0 to 464
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Title              465 non-null    object
 1   Location           465 non-null    object
 2   Security           465 non-null    int64
 3   Garage             465 non-null    int64
 4   Concierge          465 non-null    int64
 5   Description        465 non-null    object
 6   Price              465 non-null    int32
 7   City               465 non-null    object
 8   Currency           465 non-null    object
 9   Nmbr of rooms      442 non-null    object
 10  Nmbr of pieces     442 non-null    object
 11  Nmbr of bathrooms  423 non-null    object
 12  Newness            382 non-null    object
dtypes: int32(1), int64(3), object(9)
memory usage: 45.5+ KB

In [16]:
features_with_na = [features for features in data.columns if data[features].isnull().sum()>1]

for feature in features_with_na:
    print(feature ,np.round(data[feature].isnull().mean(), 4) , '% missing values')

Nmbr of rooms 0.0495 % missing values
Nmbr of pieces 0.0495 % missing values
Nmbr of bathrooms 0.0903 % missing values
Newness 0.1785 % missing values

In [17]:
data["Surface"] = data["Description"].apply(lambda x: x[0])

In [18]:
def get_surface(data):
    return data.replace('\n', '').replace('\t', '')

In [19]:
data["Surface"] = data["Surface"].apply(lambda x: get_surface(x))

In [20]:
data["Surface"] = data["Surface"].str[:-2]

In [21]:
def get_nmbr(data):
    if data == None:
        return None
    else:
        return data.split(' ')[0]

In [22]:
data["Nmbr of rooms"] = data["Nmbr of rooms"].apply(lambda x: get_nmbr(x))

In [23]:
data["Nmbr of pieces"] = data["Nmbr of pieces"].apply(lambda x: get_nmbr(x))

In [24]:
data["Nmbr of bathrooms"] = data["Nmbr of bathrooms"].apply(lambda x: get_nmbr(x))

In [25]:
data.drop('Description', inplace=True, axis=1)

In [26]:
data.head(50)

,Title,Location,Security,Garage,Concierge,Price,City,Currency,Nmbr of rooms,Nmbr of pieces,Nmbr of bathrooms,Newness,Surface
0,Appartement avec vue mer depuis toutes les pièces,Centre,0,0,0,2200000,Tanger,DH,2,3,2,Bon état,95
1,"Studio de 43m² en vente, Résidence Panama",Malabata,1,0,0,602000,Tanger,DH,1,1,1,Nouveau,43
2,Appartement de 94m² en vente Résidence Al Bahja,Tanja Balia,0,0,0,694575,Tanger,DH,3,4,2,Nouveau,94
3,Appartement de 110m² en vente Les Jardins de M...,Mesnana,0,0,0,1112000,Tanger,DH,3,4,None,Nouveau,110
4,Appartement de 75m² en vente Les Jardins de Me...,Mesnana,0,0,0,676000,Tanger,DH,2,3,None,Nouveau,75
5,Appartement avec terrasse et vue mer,De La,0,0,0,2750000,Tanger,DH,2,3,2,Bon état,129
6,Magnifique duplex avec vue panoramique sur la ...,Centre,0,0,0,3400000,Tanger,DH,2,3,3,Bon état,223
7,Superbe appartement de 128m2 avec 3 chambres,Marchan,0,0,0,1900000,Tanger,DH,3,4,2,Bon état,128
8,"Appartement de 88m² en vente, Résidence Riad Z...",Ahlane,0,0,0,580000,Tanger,DH,2,4,1,Nouveau,70
9,Appartement en vente à Ennasr. Surface totale ...,Ennasr,0,0,0,1000000,Tanger,DH,2,5,2,Bon état,100
10,Joli appartement en vente à BAYT SAHAFA,Marjane,0,0,0,780000,Tanger,DH,2,3,1,Nouveau,73
11,Appartements moyens standing a vendre,Mesnana,0,0,0,550000,Tanger,DH,2,3,1,Nouveau,66
12,Appartement moyen standing,Tanja Balia,0,0,0,403000,Tanger,DH,2,3,1,Nouveau,58
13,Appartement de 88m² en vente Complexe résident...,Route Nationale,0,0,0,651200,Tanger,DH,2,3,1,None,88
14,Vente Appartement Tanger BOULEVARD Ref: VA335,Centre,0,0,0,1240000,Tanger,DH,2,3,1,Bon état,72
15,"Studio de 45m² en vente, Résidence Panama",Malabata,1,0,0,630000,Tanger,DH,1,1,1,Nouveau,45
16,APPARTEMENT 190 m2 de 4 chambres au Boulvard,Administratif,0,0,0,11000,Tanger,DH,4,10,3,À rénover,190
17,Ne pas rater votre appartement duplex à vendre,Route Nationale,0,0,0,1496000,Tanger,DH,3,8,2,Nouveau,136
18,Appartement Vide à La Vente Nejma Tanger,Centre,0,0,0,2450000,Tanger,DH,2,3,1,Bon état,144
19,Appartement de Luxe à La Vente Corniche Tanger,De La,0,0,0,2000000,Tanger,DH,2,3,2,Nouveau,105
20,Appartement à La Vente La wilaya Tanger,Administratif,0,0,1,1220000,Tanger,DH,2,3,1,Bon état,90
21,Appartement avecTerrasse à Vendre Mojahidin Ta...,Moujahidine,0,0,0,2960000,Tanger,DH,5,6,2,Bon état,257
22,LUMINEUX Appartement au centre ville a VENDRE,Mozart,0,0,0,700000,Tanger,DH,None,None,None,None,2 Chambr
23,Appart F4 de 96 m2 prés de Patisserie Paris,Centre,0,0,0,950000,Tanger,DH,3,4,2,Bon état,97
24,Appart F3 rénové en vente à Kawacim,Du Golf,0,0,0,580000,Tanger,DH,2,3,1,Bon état,54
25,Neuf appart F3 de 163m2 vue sur mer,Manar,0,0,0,3000000,Tanger,DH,2,3,2,Nouveau,163
26,Appartement de 115m² en vente Les Jardins de M...,Mesnana,0,0,0,1228000,Tanger,DH,3,4,None,Nouveau,115
27,Appartement de 61m² en vente Les Jardins de Me...,Mesnana,0,0,0,550000,Tanger,DH,2,3,None,Nouveau,61
28,Appartement de 112m² en vente Les Jardins de M...,Mesnana,0,0,0,1128000,Tanger,DH,3,4,None,Nouveau,112
29,Appartement de 72m² en vente Les Jardins de Me...,Mesnana,0,0,0,649000,Tanger,DH,2,3,None,Nouveau,72
30,Appartement de 85m² en vente Les Jardins de Me...,Mesnana,0,0,0,761000,Tanger,DH,2,3,None,Nouveau,85
31,Vend appartement à Marjane. Superficie 89 m²,Marjane,0,0,0,515666,Tanger,DH,2,3,1,None,89
32,Vend appartement à Marjane. Superficie 83 m²,Marjane,0,0,0,483558,Tanger,DH,2,3,1,None,83
33,Appartement de 117m² en vente Complexe résiden...,Route Nationale,0,0,0,830700,Tanger,DH,2,3,1,None,117
34,Résidence kawacim (2 ch salon ),Du Golf,0,0,0,550000,Tanger,DH,2,3,1,Bon état,99
35,Magnifique Appartement à vendre à Lotinord,Marjane,0,0,0,1250000,Tanger,DH,3,4,1,Bon état,100
36,"Appartement et Duplex à Vendre, Déclaration 10...",Route Nationale,0,0,0,1564000,Tanger,DH,3,6,3,Nouveau,136
37,Exclusif: appartement au centre a vendre,Centre,0,0,0,700000,Tanger,DH,2,3,1,Bon état,71
38,"Appartement de 109m² en vente, Résidence Qamar",Mister Khouch,0,0,0,1362500,Tanger,DH,3,4,3,None,109
39,Bel appartement haut standing A vendre: AV15,Centre,0,0,0,2280000,Tanger,DH,3,6,2,Nouveau,120
40,Des Appartements haut standing à Malabata. Tanger,Tanja Balia,0,0,0,950000,Tanger,DH,None,None,None,Nouveau,2 Pièc
41,"Studio de 50m² en vente, Résidence Panama",Malabata,1,0,0,700000,Tanger,DH,1,1,1,Nouveau,50
42,Appartement moderne dans le quartier de Malabata,Centre,0,0,0,2332000,Tanger,DH,2,5,2,Bon état,146
43,Magnifique Riad traditionnel,Médina,0,0,0,7725000,Tanger,DH,8,14,1,Bon état,300
44,Grand appartement de 3 chambres,Centre,0,0,0,1500000,Tanger,DH,3,5,1,Bon état,117
45,Un appartement de 160 mètres carrés dans le ce...,Mozart,0,0,0,1526400,Tanger,DH,3,5,1,Bon état,160
46,Un magnifique appartement de style colonial,Médina,0,0,0,1550000,Tanger,DH,3,5,1,Bon état,144
47,Appartement de 115m2 avec un grand potentiel,Mozart,0,0,0,1097100,Tanger,DH,3,5,1,Bon état,115
48,Appartement à l'achat à De La Plage. 2 chambre...,De La,0,0,0,1890000,Tanger,DH,2,3,2,Nouveau,105
49,Appartement de 88m² en vente Complexe résident...,Route Nationale,0,0,0,651200,Tanger,DH,2,3,1,None,88

In [27]:
data = data.dropna()
data.reset_index(drop=True, inplace=True)

In [28]:
data["Nmbr of rooms"] = data["Nmbr of rooms"].astype('int64')
data["Nmbr of pieces"] = data["Nmbr of pieces"].astype('int64')
data["Nmbr of bathrooms"] = data["Nmbr of bathrooms"].astype('int64')

In [29]:
data.to_csv("new_df.csv")

In [30]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 359 entries, 0 to 358
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Title              359 non-null    object
 1   Location           359 non-null    object
 2   Security           359 non-null    int64
 3   Garage             359 non-null    int64
 4   Concierge          359 non-null    int64
 5   Price              359 non-null    int32
 6   City               359 non-null    object
 7   Currency           359 non-null    object
 8   Nmbr of rooms      359 non-null    int64
 9   Nmbr of pieces     359 non-null    int64
 10  Nmbr of bathrooms  359 non-null    int64
 11  Newness            359 non-null    object
 12  Surface            359 non-null    object
dtypes: int32(1), int64(6), object(6)
memory usage: 35.2+ KB